### ISSUE TITLE
Site certificate needs renewed

### ISSUE THREAD

**Issue by jaredbrogan** [tomaustin700/YAMLPipelineValidator#8]
The site's ssl certificate has expired and needs renewed.
![image](https://user-images.githubusercontent.com/42228088/193654936-39fc94d4-4dff-435f-8ed6-13c40a958d57.png)

![image](https://user-images.githubusercontent.com/42228088/193654866-a2c18963-8ca1-48e8-bb01-51fd4ca75dc3.png)

**Comment by tomaustin700** [comment]
@jaredbrogan Thanks for letting me know, looking at this now.

**Comment by tomaustin700** [comment]
Issue should now be resolved
